### PR TITLE
set include_vinyl_count to false by default

### LINKED ISSUE #22: include_vinyl_count should be false by default
`include_vinyl_count` option should be `false` by default because it hits performance and causes latency spikes when spaces contain much data.

Moreover, people who have been using `stat` package for monitoring purposes may get latency problems after upgrading `stat` to the recent version from the old one.

### PR DESCRIPTION
**Pull request by bofm**
fixes #22

### CODE REVIEW

**Review by Totktonada — APPROVED** [review]
I have no objections. @sharonovd can you look, please?

**Comment by sharonovd** [comment]
I see no reason to do this, this behaviour is the same from the very first release.
Moreover, if this change is accepted, this will break backward compatibility.

**Comment by Totktonada** [comment]
The compatibility is matter, okay. So I propose to add a note about possible latency spikes with much data in vinyl when the default value is used.

**Comment by sharonovd** [comment]
> The compatibility is matter, okay. So I propose to add a note about possible latency spikes with much data in vinyl when the default value is used.

Yes, looks fine for me.

**Comment by Totktonada** [comment]
The module is [deprecated](https://github.com/tarantool/stat/commit/9b39a075ef59bc52754486511cb8cb44e46540f5) in favor of [metrics](https://github.com/tarantool/metrics), so I'll close the PR.

**Pull request closed without merging**
